# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CardManage' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'AFNetworking'
  pod 'YYKit'
  pod 'FMDB'
  pod 'Masonry'
  pod 'MBProgressHUD'
  # 跑马灯
  pod 'TXScrollLabelView'
  # 带动画的弹框
  pod 'ZJAnimationPopView'
  # 网络指示器
  pod 'MBProgressHUD'

  # Pods for CardManage

  target 'CardManageTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CardManageUITests' do
    inherit! :search_paths
    # Pods for testing
  end
end
